import BlocksField from "./BlocksField.vue";
import ButtonsField from "./ButtonsField.vue";
import CheckboxesField from "./CheckboxesField.vue";
import ColorField from "./ColorField.vue";
import DateField from "./DateField.vue";
import EmailField from "./EmailField.vue";
import EntriesField from "./EntriesField.vue";
import FilePickerField from "./FilePickerField.vue";
import GapField from "./GapField.vue";
import HeadlineField from "./HeadlineField.vue";
import InfoField from "./InfoField.vue";
import LayoutField from "./LayoutField.vue";
import LineField from "./LineField.vue";
import LinkField from "./LinkField.vue";
import ListField from "./ListField.vue";
import MultiselectField from "./MultiselectField.vue";
import NumberField from "./NumberField.vue";
import ObjectField from "./ObjectField.vue";
import PagePickerField from "./PagePickerField.vue";
import PasswordField from "./PasswordField.vue";
import RadioField from "./RadioField.vue";
import RangeField from "./RangeField.vue";
import SelectField from "./SelectField.vue";
import SlugField from "./SlugField.vue";
import StatsField from "./StatsField.vue";
import StructureField from "./StructureField.vue";
import TagsField from "./TagsField.vue";
import TelField from "./TelField.vue";
import TextField from "./TextField.vue";
import TextareaField from "./TextareaField.vue";
import TimeField from "./TimeField.vue";
import ToggleField from "./ToggleField.vue";
import TogglesField from "./TogglesField.vue";
import UrlField from "./UrlField.vue";
import UserPickerField from "./UserPickerField.vue";
import WriterField from "./WriterField.vue";

// @deprecated
import LegacyFilesField from "./LegacyFilesField.vue";
import LegacyModelsField from "./LegacyModelsField.vue";
import LegacyPagesField from "./LegacyPagesField.vue";
import LegacyUsersField from "./LegacyUsersField.vue";

export default {
	install(app) {
		app.component("k-blocks-field", BlocksField);
		app.component("k-buttons-field", ButtonsField);
		app.component("k-checkboxes-field", CheckboxesField);
		app.component("k-color-field", ColorField);
		app.component("k-date-field", DateField);
		app.component("k-email-field", EmailField);
		app.component("k-entries-field", EntriesField);
		app.component("k-files-field", FilePickerField);
		app.component("k-gap-field", GapField);
		app.component("k-headline-field", HeadlineField);
		app.component("k-info-field", InfoField);
		app.component("k-layout-field", LayoutField);
		app.component("k-line-field", LineField);
		app.component("k-link-field", LinkField);
		app.component("k-list-field", ListField);
		app.component("k-multiselect-field", MultiselectField);
		app.component("k-number-field", NumberField);
		app.component("k-object-field", ObjectField);
		app.component("k-pages-field", PagePickerField);
		app.component("k-password-field", PasswordField);
		app.component("k-radio-field", RadioField);
		app.component("k-range-field", RangeField);
		app.component("k-select-field", SelectField);
		app.component("k-slug-field", SlugField);
		app.component("k-stats-field", StatsField);
		app.component("k-structure-field", StructureField);
		app.component("k-tags-field", TagsField);
		app.component("k-text-field", TextField);
		app.component("k-textarea-field", TextareaField);
		app.component("k-tel-field", TelField);
		app.component("k-time-field", TimeField);
		app.component("k-toggle-field", ToggleField);
		app.component("k-toggles-field", TogglesField);
		app.component("k-url-field", UrlField);
		app.component("k-users-field", UserPickerField);
		app.component("k-writer-field", WriterField);

		// Legacy fields components
		// @deprecated
		app.component("k-legacy-checkboxes-field", CheckboxesField);
		app.component("k-legacy-color-field", ColorField);
		app.component("k-legacy-date-field", DateField);
		app.component("k-legacy-email-field", EmailField);
		app.component("k-legacy-files-field", LegacyFilesField);
		app.component("k-legacy-gap-field", GapField);
		app.component("k-legacy-headline-field", HeadlineField);
		app.component("k-legacy-info-field", InfoField);
		app.component("k-legacy-line-field", LineField);
		app.component("k-legacy-link-field", LinkField);
		app.component("k-legacy-list-field", ListField);
		app.component("k-legacy-object-field", ObjectField);
		app.component("k-legacy-models-field", LegacyModelsField);
		app.component("k-legacy-multiselect-field", MultiselectField);
		app.component("k-legacy-number-field", NumberField);
		app.component("k-legacy-pages-field", LegacyPagesField);
		app.component("k-legacy-radio-field", RadioField);
		app.component("k-legacy-select-field", SelectField);
		app.component("k-legacy-slug-field", SlugField);
		app.component("k-legacy-structure-field", StructureField);
		app.component("k-legacy-tags-field", TagsField);
		app.component("k-legacy-tel-field", TelField);
		app.component("k-legacy-text-field", TextField);
		app.component("k-legacy-textarea-field", TextareaField);
		app.component("k-legacy-time-field", TimeField);
		app.component("k-legacy-toggle-field", ToggleField);
		app.component("k-legacy-toggles-field", TogglesField);
		app.component("k-legacy-url-field", UrlField);
		app.component("k-legacy-users-field", LegacyUsersField);
		app.component("k-legacy-writer-field", WriterField);
	}
};
