import Vue from "vue";

import AspectRatio from "./AspectRatio.vue";
import Bar from "./Bar.vue";
import Box from "./Box.vue";
import Bubble from "./Bubble.vue";
import Bubbles from "./Bubbles.vue";
import Collection from "./Collection.vue";
import Column from "./Column.vue";
import Dropzone from "./Dropzone.vue";
import Empty from "./Empty.vue";
import FilePreview from "./FilePreview.vue";
import Grid from "./Grid.vue";
import Header from "./Header.vue";
import Inside from "./Inside.vue";
import Item from "./Item.vue";
import ItemImage from "./ItemImage.vue";
import Items from "./Items.vue";
import Overlay from "./Overlay.vue";
import Panel from "./Panel.vue";
import Stats from "./Stats.vue";
import Table from "./Table.vue";
import TableCell from "./TableCell.vue";
import TableUpdateStatusCell from "./TableUpdateStatusCell.vue";
import Tabs from "./Tabs.vue";
import View from "./View.vue";

Vue.component("k-aspect-ratio", AspectRatio);
Vue.component("k-bar", Bar);
Vue.component("k-box", Box);
Vue.component("k-bubble", Bubble);
Vue.component("k-bubbles", Bubbles);
Vue.component("k-collection", Collection);
Vue.component("k-column", Column);
Vue.component("k-dropzone", Dropzone);
Vue.component("k-empty", Empty);
Vue.component("k-file-preview", FilePreview);
Vue.component("k-grid", Grid);
Vue.component("k-header", Header);
Vue.component("k-inside", Inside);
Vue.component("k-item", Item);
Vue.component("k-item-image", ItemImage);
Vue.component("k-items", Items);
Vue.component("k-overlay", Overlay);
Vue.component("k-panel", Panel);
Vue.component("k-stats", Stats);
Vue.component("k-table", Table);
Vue.component("k-table-cell", TableCell);
Vue.component("k-table-update-status-cell", TableUpdateStatusCell);
Vue.component("k-tabs", Tabs);
Vue.component("k-view", View);
