import AspectRatio from "./AspectRatio.vue";
import Bar from "./Bar.vue";
import Box from "./Box.vue";
import Bubble from "./Bubble.vue";
import Bubbles from "./Bubbles.vue";
import Collection from "./Collection.vue";
import Column from "./Column.vue";
import Dropzone from "./Dropzone.vue";
import Empty from "./Empty.vue";
import Frame from "./Frame/Frame.vue";
import FilePreview from "./FilePreview.vue";
import Grid from "./Grid.vue";
import Header from "./Header.vue";
import IconFrame from "./Frame/IconFrame.vue";
import ImageFrame from "./Frame/ImageFrame.vue";
import Inside from "./Inside.vue";
import Item from "./Item.vue";
import ItemImage from "./ItemImage.vue";
import Items from "./Items.vue";
import Overlay from "./Overlay.vue";
import Panel from "./Panel.vue";
import Stats from "./Stats.vue";
import Table from "./Table.vue";
import TableCell from "./TableCell.vue";
import TableUpdateStatusCell from "./TableUpdateStatusCell.vue";
import Tabs from "./Tabs.vue";
import View from "./View.vue";

export default {
	install(app) {
		app.component("k-aspect-ratio", AspectRatio);
		app.component("k-bar", Bar);
		app.component("k-box", Box);
		app.component("k-bubble", Bubble);
		app.component("k-bubbles", Bubbles);
		app.component("k-collection", Collection);
		app.component("k-column", Column);
		app.component("k-dropzone", Dropzone);
		app.component("k-empty", Empty);
		app.component("k-file-preview", FilePreview);
		app.component("k-frame", Frame);
		app.component("k-grid", Grid);
		app.component("k-header", Header);
		app.component("k-inside", Inside);
		app.component("k-icon-frame", IconFrame);
		app.component("k-image-frame", ImageFrame);
		app.component("k-image", ImageFrame);
		app.component("k-item", Item);
		app.component("k-item-image", ItemImage);
		app.component("k-items", Items);
		app.component("k-overlay", Overlay);
		app.component("k-panel", Panel);
		app.component("k-stats", Stats);
		app.component("k-table", Table);
		app.component("k-table-cell", TableCell);
		app.component("k-table-update-status-cell", TableUpdateStatusCell);
		app.component("k-tabs", Tabs);
		app.component("k-view", View);
	}
};
