title: Product

columns:
	- 1/3: image
	- 2/3: data

sections:

	# all images displayed as nice cards
	image:
		headline: Image
		type: files
		query: page.images
		layout: cards
		item:
			image:
				ratio: 1/1
				back: pattern
		min: 1
		max: 1
		accept: image/jpeg

	# the form for the page
	data:
		type: fields
		fields:
			price:
				label: Price
				type: text
			design:
				label: Design by …
				type: text
			sizes:
				label: Sizes
				type: checkboxes
				default:
					- S
					- M
					- L
					- XL
					- XXL
				options:
					- S
					- M
					- L
					- XL
					- XXL
			link:
				label: Link
				type: url
			description:
				label: Description
				type: textarea
