name: Setup Node/npm
description: Shared steps to set up Node & npm

runs:
  using: composite
  steps:
    - name: Set up Node.js and cache npm dependencies
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 22
        cache: "npm"
        cache-dependency-path: panel/package-lock.json

    - name: Install npm dependencies
      shell: bash
      working-directory: panel
      run: npm ci
