import Vue from "vue";

import CheckboxInput from "@/components/Forms/Input/CheckboxInput.vue";
import CheckboxesInput from "@/components/Forms/Input/CheckboxesInput.vue";
import DateInput from "@/components/Forms/Input/DateInput.vue";
import EmailInput from "@/components/Forms/Input/EmailInput.vue";
import ListInput from "@/components/Forms/Input/ListInput.vue";
import MultiselectInput from "@/components/Forms/Input/MultiselectInput.vue";
import NumberInput from "@/components/Forms/Input/NumberInput.vue";
import PasswordInput from "@/components/Forms/Input/PasswordInput.vue";
import RadioInput from "@/components/Forms/Input/RadioInput.vue";
import RangeInput from "@/components/Forms/Input/RangeInput.vue";
import SelectInput from "@/components/Forms/Input/SelectInput.vue";
import SlugInput from "@/components/Forms/Input/SlugInput.vue";
import TagsInput from "@/components/Forms/Input/TagsInput.vue";
import TelInput from "@/components/Forms/Input/TelInput.vue";
import TextInput from "@/components/Forms/Input/TextInput.vue";
import TextareaInput from "@/components/Forms/Input/TextareaInput.vue";
import TimeInput from "@/components/Forms/Input/TimeInput.vue";
import ToggleInput from "@/components/Forms/Input/ToggleInput.vue";
import TogglesInput from "@/components/Forms/Input/TogglesInput.vue";
import UrlInput from "@/components/Forms/Input/UrlInput.vue";

Vue.component("k-checkbox-input", CheckboxInput);
Vue.component("k-checkboxes-input", CheckboxesInput);
Vue.component("k-date-input", DateInput);
Vue.component("k-email-input", EmailInput);
Vue.component("k-list-input", ListInput);
Vue.component("k-multiselect-input", MultiselectInput);
Vue.component("k-number-input", NumberInput);
Vue.component("k-password-input", PasswordInput);
Vue.component("k-radio-input", RadioInput);
Vue.component("k-range-input", RangeInput);
Vue.component("k-select-input", SelectInput);
Vue.component("k-slug-input", SlugInput);
Vue.component("k-tags-input", TagsInput);
Vue.component("k-tel-input", TelInput);
Vue.component("k-text-input", TextInput);
Vue.component("k-textarea-input", TextareaInput);
Vue.component("k-time-input", TimeInput);
Vue.component("k-toggle-input", ToggleInput);
Vue.component("k-toggles-input", TogglesInput);
Vue.component("k-url-input", UrlInput);
