import Vue from "vue";

import Draggable from "./Draggable.vue";
import ErrorBoundary from "./ErrorBoundary.vue";
import Fatal from "./Fatal.vue";
import Headline from "./Headline.vue";
import Icon from "./Icon.vue";
import Icons from "./Icons.vue";
import Image from "./Image.vue";
import Loader from "./Loader.vue";
import OfflineWarning from "./OfflineWarning.vue";
import Progress from "./Progress.vue";
import Registration from "./Registration.vue";
import SortHandle from "./SortHandle.vue";
import StatusIcon from "./StatusIcon.vue";
import Text from "./Text.vue";
import UserInfo from "./UserInfo.vue";

Vue.component("k-draggable", Draggable);
Vue.component("k-error-boundary", ErrorBoundary);
Vue.component("k-fatal", Fatal);
Vue.component("k-headline", Headline);
Vue.component("k-icon", Icon);
Vue.component("k-icons", Icons);
Vue.component("k-image", Image);
Vue.component("k-loader", Loader);
Vue.component("k-offline-warning", OfflineWarning);
Vue.component("k-progress", Progress);
Vue.component("k-registration", Registration);
Vue.component("k-status-icon", StatusIcon);
Vue.component("k-sort-handle", SortHandle);
Vue.component("k-text", Text);
Vue.component("k-user-info", UserInfo);
