<template>
	<component
		:is="$panel.dialog.component"
		:key="$panel.dialog.timestamp"
		ref="dialog"
		v-bind="$panel.dialog.props"
		:disabled="$panel.dialog.isLoading"
		:visible="true"
	/>
</template>
