name: Setup PHP
description: Shared steps to set up PHP and cache extensions

inputs:
  php:
    required: true
  extensions:
    required: false
    default: "mbstring, ctype, curl, gd, apcu, memcached, redis"
  ini:
    required: false
    default: ""
  coverage:
    default: none
  tools:
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup PHP cache environment
      if: inputs.extensions != ''
      id: php-cache
      uses: shivammathur/cache-extensions@256729b5fef535345e27904657f78048c0990f81 # v1
      with:
        php-version: ${{ inputs.php }}
        extensions: ${{ inputs.extensions }}
        key: php-v1

    - name: Cache PHP extensions
      if: inputs.extensions != ''
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ${{ steps.php-cache.outputs.dir }}
        key: ${{ steps.php-cache.outputs.key }}

    - name: Setup PHP environment
      id: php-setup
      uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
      with:
        php-version: ${{ inputs.php }}
        extensions: ${{ inputs.extensions }}
        ini-values: ${{ inputs.ini }}
        coverage: ${{ inputs.coverage }}
        tools: ${{ inputs.tools }}
