title: About
layout:
  -
    width: 2/3
    sections:
      -
        type: fields
        fields:
          -
            label: Intro
            name: intro
            type: textarea
          -
            label: Text
            name: text
            type: textarea
  -
    width: 1/3
    sections:
      -
        headline: Images
        type: files
