title: Project

layout:
  -
    width: 2/3
    sections:
      -
        type: fields
        fields:
          -
            label: Year
            name: year
            type: text
            width: 1/2
          -
            label: Client
            name: client
            type: text
            width: 1/2
          -
            label: Category
            name: category
            type: tags
          -
            label: Budget
            name: budget
            type: range
            step: 1000
            max: 10000
            before: "$"
            required: true
          -
            label: Introduction
            name: intro
            type: textarea
            buttons: false
          -
            label: Text
            name: text
            type: textarea

  -
    width: 1/3
    sections:
      -
        headline: Cover
        type: files
        layout: cards
        group: cover
        max: 1
        add: image/jpeg
        fields:
          -
            name: alt
            label: Alt Text
            type: text
            width: 1/2
          -
            name: photographer
            label: Photographer
            type: text
            width: 1/2
          -
            name: caption
            label: Caption
            type: textarea

      -
        headline: Images
        type: files
        group: gallery
        max: 5
        add: image/*
        fields:
          -
            name: alt
            label: Alt Text
            type: text
            width: 1/2
          -
            name: photographer
            label: Photographer
            type: text
            width: 1/2
