title: Project
layout:
  -
    width: 2/3
    sections:
      -
        type: fields
        fields:
          -
            label: Year
            name: year
            type: text
            width: 1/2
          -
            label: Client
            name: client
            type: text
            width: 1/2
          -
            label: Category
            name: category
            type: tags
          -
            label: Introduction
            name: intro
            type: textarea
          -
            label: Text
            name: text
            type: textarea
  -
    width: 1/3
    sections:
      -
        headline: Cover
        type: files
        layout: cards
        pagination:
          hide: true
          page: 1
          limit: 1
      -
        headline: Images
        type: files
