title: Site

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - 1/1: projects, blog, about, misc
  social:
    label: Social
    icon: twitter
    columns:
      - 1/1: social
  seo:
    label: SEO
    icon: search
    columns:
      - 1/1: seo

sections:

  projects:
    headline: Projects
    type: pages
    query: site.find("projects").children.visible
    layout: list
    create: project

  blog:
    headline: Blog
    type: pages
    query: site.find('blog').children.visible
    layout: list
    item:
      info: "{{ page.date('d.m.Y') }}"
    create: article

  about:
    headline: About
    type: pages
    query: site.find('about').children
    layout: list
    item:
      info: "{{ page.position }}"
    create: team

  misc:
    headline: Misc
    type: pages
    query: site.find('home', 'contact', 'form')
    item:
      image: false

  social:
    type: fields
    fields:
      twitter:
        label: Twitter Account
        type: text
        icon: twitter
      facebook:
        label: Facebook Account
        type: text
        icon: facebook

  seo:
    type: fields
    fields:
      metaTitle:
        label: Meta Title
        type: text
      metaDescription:
        label: Meta Description
        type: textarea
