title: Site

tabs:
  pages:
    label:
      en: Pages
      de: Seiten
    icon: page
    columns:
      - 1/1: kitchensink
  footer:
    label: Footer
    icon: twitter
    columns:
      - 1/1: footer
  seo:
    label: SEO
    icon: search
    columns:
      - 2/3: seoContent
      - 1/3: seoImages
  taxonomy:
    label: Taxonomy
    icon: tag
    columns:
      - 1/1: tags

sections:

  # PAGES TAB
  kitchensink:
    headline: Examples
    type: pages
    status: listed
    item:
      image: false
      info: "{{ page.template }}"

  # FOOTER TAB
  footer:
    type: fields
    fields:
      copyright:
        label: Copyright
        type: text
        before: ©
      twitter:
        label: Twitter Account
        type: text
        icon: twitter
        width: 1/2
        before: "@"
      instagram:
        label: Instagram Account
        type: text
        icon: instagram
        width: 1/2

  # SEO TAB
  seoContent:
    type: fields
    fields:
      metaTitle:
        label: Meta Title
        type: text
        required: true
      metaDescription:
        label: Meta Description
        type: textarea
        buttons: false

  seoImages:
    type: files
    headline: Seo Images
    min: 1

  # TAXONOMY TAB
  tags:
    type: fields
    fields:
      tags:
        label: Tags
        type: structure
        fields:
          name:
            label: Tag
            type: text
            width: 1/2
          value:
            label: Value
            type: text
            width: 1/2
