title: Site
layout:
  -
    width: 1/1
    sections:
      -
        headline: Projects
        type: pages
        pages: site.find('projects').children
        info: "{{ page.year }}"
        layout: list
        add: project
      -
        headline: Blog
        type: pages
        pages: site.find('blog').children.flip
        info: "{{ page.date('d.m.Y') }}"
        layout: list
        add: article
      -
        headline: About
        type: pages
        pages: site.find('about').children
        info: "{{ page.position }}"
        layout: list
        add: team
      -
        headline: Misc
        type: pages
        pages: site.find('home', 'contact')
        layout: list
        image: false
        add: default
