title: Site

tabs:
  pages:
    label: Pages
    icon: page
    columns:
      - 1/1: projects, blog, about, kitchensink, misc
  social:
    label: Social
    icon: twitter
    columns:
      - 1/1: social
  seo:
    label: SEO
    icon: search
    columns:
      - 1/1: seo

sections:

  projects:
    extends: sections/projects
    layout: list

  blog:
    extends: sections/articles

  about:
    extends: sections/team
    headline: About

  kitchensink:
    headline: Kitchensink
    type: pages
    parent: site.find("kitchensink")
    item:
      image: false

  misc:
    headline: Misc
    type: pages
    templates:
      - home
      - contact
    item:
      image: false

  social:
    type: fields
    fields:
      twitter:
        label: Twitter Account
        type: text
        icon: twitter
      facebook:
        label: Facebook Account
        type: text
        icon: facebook

  seo:
    type: fields
    fields:
      metaTitle:
        label: Meta Title
        type: text
      metaDescription:
        label: Meta Description
        type: textarea
