<?php

namespace Kirby\Auth;

use Kirby\Cms\App;
use Kirby\Cms\User;
use Kirby\Toolkit\Str;
use SensitiveParameter;

/**
 * Base class for authentication challenges
 * that create and verify e.g. one-time auth codes
 *
 * @package   Kirby Auth
 * @author    Lukas Bestle <lukas@getkirby.com>
 * @link      https://getkirby.com
 * @copyright Bastian Allgeier
 * @license   https://getkirby.com/license
 * @since     6.0.0
 */
abstract class Challenge
{
	protected App $kirby;

	public function __construct(
		protected User $user,
		protected string $mode,
		protected int $timeout
	) {
		$this->kirby = $user->kirby();
	}

	/**
	 * Generates a random one-time auth code or similar challenge data
	 * and returns it for later verification.
	 *
	 * Return a Pending data object or null
	 * if nothing was generated by this algorithm.
	 */
	abstract public function create(): Pending|null;

	/**
	 * Checks whether the challenge is available
	 * for the specific user and purpose
	 *
	 * @param \Kirby\Cms\User $user User the code will be generated for
	 * @param 'login'|'password-reset'|'2fa' $mode Purpose of the code
	 */
	public static function isAvailable(User $user, string $mode): bool
	{
		return true;
	}

	/**
	 * Checks whether the challenge is generally enabled on this site
	 */
	public static function isEnabled(Auth $auth): bool
	{
		return true;
	}

	/**
	 * Returns the purpose of the challenge
	 * @return 'login'|'password-reset'|'2fa'
	 */
	public function mode(): string
	{
		return $this->mode;
	}

	/**
	 * Returns the number of seconds the code will be valid for
	 */
	public function timeout(): int
	{
		return $this->timeout;
	}

	public function type(): string
	{
		return Str::camelToKebab(lcfirst(basename(str_replace(['\\', 'Challenge'], ['/', ''], static::class))));
	}

	/**
	 * Returns the user the challenge belongs to
	 */
	public function user(): User
	{
		return $this->user;
	}

	/**
	 * Verifies the provided input
	 */
	abstract public function verify(
		#[SensitiveParameter]
		mixed $input,
		Pending $data
	): bool;
}
